-------------------------
-- Bulgarian Localization String resources
-- MIUI.BG (2014)
-- tmladenov
-------------------------
localization_Bulgarian_table = {
    calories_table={
        {str="≈ Краставица (100г)", calories=14},
        {str="≈ Пилешки бульон (100г)", calories=15},
        {str="≈ Зеле (100г)", calories=16},
        {str="≈ Мариновани домати (100г)", calories=19},
        {str="≈ Гъби (100г)", calories=20},
        {str="≈ Репички (100г)", calories=21},
        {str="≈ Патладжан (100г)", calories=24},
        {str="≈ Тиква (100г)", calories=25},
        {str="≈ Кисело зеле (100г)", calories=25},
        {str="≈ Гъбена супа (100г)", calories=26},
        {str="≈ Броколи (100г)", calories=27},
        {str="≈ Зеленчукова супа (100г)", calories=28},
        {str="≈ Ягоди (100г)", calories=30},
        {str="≈ Борш (100г)", calories=36},
        {str="≈ Месна супа (100г)", calories=36},
        {str="≈ Цвекло (100г)", calories=36},
        {str="≈ Ябълка (100г)", calories=37},
        {str="≈ Портокал (100г)", calories=38},
        {str="≈ Картофена супа (100г)", calories=39},
        {str="≈ Диня (100г)", calories=39},
        {str="≈ Супа от киселец (100г)", calories=40},
        {str="≈ Мътеница 1% (100г)", calories=40},
        {str="≈ Coca-Cola (100г)", calories=42},
        {str="≈ Мляко 1.5% (100г)", calories=45},
        {str="≈ Red Bull (100г)", calories=45},
        {str="≈ Крем-супа (100г)", calories=46},
        {str="≈ Праскови (100г)", calories=46},
        {str="≈ Сирене Hochland (25г)", calories=48},
        {str="≈ Череши (100г)", calories=52},
        {str="≈ Портокалов сок (100г)", calories=54},
        {str="≈ Мляко 3.2% (100г)", calories=58},
        {str="≈ Рататуи (100г)", calories=60},
        {str="≈ Картофено пюре (100г)", calories=65},
        {str="≈ Грахова супа (100г)", calories=66},
        {str="≈ Манго (100г)", calories=67},
        {str="≈ Супа от леща (100г)", calories=68},
        {str="≈ Ягодово желе (100г)", calories=69},
        {str="≈ Кисело мляко 1.5% (100г)", calories=70},
        {str="≈ Рулца от раци (100г)", calories=73},
        {str="≈ Калмари (100г)", calories=75},
        {str="≈ Шампанско (100г)", calories=76},
        {str="≈ Вино 13% (100г)", calories=78},
        {str="≈ Гулаш с зеле (100г)", calories=81},
        {str="≈ Варени картофи (100г)", calories=82},
        {str="≈ Абсент 60% ​​(100г)", calories=83},
        {str="≈ Карт. пюре с мляко (100г)", calories=85},
        {str="≈ Сварено яйце (55g)", calories=88},
        {str="≈ Банан (100г)", calories=89},
        {str="≈ Боб с домати (100г)", calories=92},
        {str="≈ Кетчуп (100г)", calories=93},
        {str="≈ Ориз със зеленчуци (100г)", calories=94},
        {str="≈ Препечен хляб (1 филия)", calories=95},
        {str="≈ Риба тон (100г)", calories=96},
        {str="≈ Варен омар (100г)", calories=97},
        {str="≈ Зеленчукова яхния (100г)", calories=99},
        {str="≈ Варен шаран (100г)", calories=102},
        {str="≈ Плодова салата (100г)", calories=103},
        {str="≈ Пуешко филе (100г)", calories=104},
        {str="≈ Есетрова риба (100г)", calories=105},
        {str="≈ Ориз (100г)", calories=113},
        {str="≈ Цепелини (100г)", calories=117},
        {str="≈ Бъркани яйца", calories=119},
        {str="≈ Салата от тиквички (100г)", calories=122},
        {str="≈ Японска майонеза (100г)", calories=134},
        {str="≈ Marshmallow (1бр)", calories=135},
        {str="≈ Извара (100г)", calories=136},
        {str="≈ Авокадо", calories=140},
        {str="≈ Капучино (100г)", calories=140},
        {str="≈ Боб по грузински (100г)", calories=141},
        {str="≈ Телешки език (100г)", calories=146},
        {str="≈ Телешки гулаш (100г)", calories=148},
        {str="≈ Варено пилешко филе (100г)", calories=153},
        {str="≈ Пържени картофи (100г)", calories=154},
        {str="≈ Пица Маргарита (100г)", calories=157},
        {str="≈ Кюфтета (100г)", calories=159},
        {str="≈ Елда (100г)", calories=160},
        {str="≈ Ръжен хляб (100г)", calories=165},
        {str="≈ Печена пуйка (100г)", calories=165},
        {str="≈ Пушено пиле (100г)", calories=184},
        {str="≈ Свинско месо (100г)", calories=195},
        {str="≈ Колбас (100г)", calories=198},
        {str="≈ Сьомга (201g)", calories=201},
        {str="≈ Заквасена сметана 20% (100г)", calories=204},
        {str="≈ Сметана (100г)", calories=206},
        {str="≈ Спагети Болонезе (100г)", calories=208},
        {str="≈ Черен хляб (100г)", calories=214},
        {str="≈ Захаросани плодове (100г)", calories=216},
        {str="≈ Солена херинга (100г)", calories=217},
        {str="≈ Гъбен Жулиен (100г)", calories=219},
        {str="≈ Салата Цезар (100г)", calories=221},
        {str="≈ Омлет (100г)", calories=222},
        {str="≈ Светла бира (0.5л)", calories=225},
        {str="≈ Овесен хляб (100г)", calories=226},
        {str="≈ Агнешко задушено (100г)", calories=226},
        {str="≈ Мелба (100г)", calories=227},
        {str="≈ McD Хамбургер", calories=229},
        {str="≈ Свинско печено (100г)", calories=233},
        {str="≈ Бял хляб (100г)", calories=235},
        {str="≈ Питка (100г)", calories=236},
        {str="≈ Водка 40% (100г)", calories=237},
        {str="≈ Пастърма (100г)", calories=240},
        {str="≈ Испанска шунка (100г)", calories=241},
        {str="≈ Равиоли (100г)", calories=245},
        {str="≈ Червен хайвер (100г)", calories=249},
        {str="≈ Пилешки дюнер (100г)", calories=250},
        {str="≈ Пилешки колбас (100г)", calories=259},
        {str="≈ Котлети (100г)", calories=260},
        {str="≈ Стафиди (100г)", calories=262},
        {str="≈ McD Чийзбургер", calories=264},
        {str="≈ Млечни продукти (100г)", calories=270},
        {str="≈ Шунка (100г)", calories=270},
        {str="≈ Аншоа пушена (100г)", calories=270},
        {str="≈ McD McNuggets (100г)", calories=272},
        {str="≈ Кнедли (100г)", calories=275},
        {str="≈ Сьомга на скара (100г)", calories=283},
        {str="≈ Черен хайвер (100г)", calories=289},
        {str="≈ Майонеза (100г)", calories=299},
        {str="≈ Мед (100г)", calories=302},
        {str="≈ McD картофи (100 g)", calories=303},
        {str="≈ Фурми (100г)", calories=306},
        {str="≈ Ябълкови палачинки (100г)", calories=306},
        {str="≈ Зелеви сърми (100г)", calories=311},
        {str="≈ Палачинки (100г)", calories=322},
        {str="≈ Омлет със сирене (100г)", calories=324},
        {str="≈ Кървавица (100г)", calories=326},
        {str="≈ Понички (100г)", calories=329},
        {str="≈ Чийзкейк (100г)", calories=331},
        {str="≈ Палачинки с масло (100г)", calories=332},
        {str="≈ Кебап (100г)", calories=339},
        {str="≈ Спагети (100г)", calories=344},
        {str="≈ Кифла (100г)", calories=345},
        {str="≈ Меденки (100г)", calories=350},
        {str="≈ Бьоф Строганов (100г)", calories=355},
        {str="≈ Корнфлейкс (100г)", calories=363},
        {str="≈ Тестени изделия (100г)", calories=371},
        {str="≈ Пържола (100г)", calories=384},
        {str="≈ Бисквити (100г)", calories=386},
        {str="≈ Захар (100г)", calories=398},
        {str="≈ Овесени бисквити (100г)", calories=440},
        {str="≈ Шницел (100г)", calories=456},
        {str="≈ Лазаня (100г)", calories=460},
        {str="≈ Гъши дроб (100г)", calories=462},
        {str="≈ Торта (100г)", calories=478},
        {str="≈ Пуканки (100г)", calories=480},
        {str="≈ Twix", calories=483},
        {str="≈ Snickers", calories=497},
        {str="≈ Бекон (100г)", calories=500},
        {str="≈ McD Big Mac", calories=510},
        {str="≈ Чипс Lays Max (100г)", calories=510},
        {str="≈ KitKat", calories=524},
        {str="≈ Тирамису (100г)", calories=540},
        {str="≈ Чипс Pringles (100г)", calories=540},
        {str="≈ Шоколад (100г)", calories=546},
        {str="≈ Сладкиш Наполеон (100г)", calories=552},
        {str="≈ Салам (100г)", calories=568},
        {str="≈ Печена гъска (100г)", calories=620},
        {str="≈ Пържени кнедли (100г)", calories=764},
        {str="≈ McD Big Tasty", calories=850},
    },

    ok='OK',

    hour='ч',
    minute='мин',
    month='месец',
    day='ден',
    step="крачка",
    km='км',
    minute_format='%dмин',
    hour_minute_format='%dч %dмин',
    hour_format='%dч',

    welcome_use="Здравей, аз съм твоята Mi Band.",
    last_week_walked_format='През последната седмица извървяхте %d крачки.',
    last_week_walked_info_format='Извървяхте %d км, изгорихте %d cal.',
    last_month_walked_format='През последния месец извървяхте %d крачки.',
    last_month_walked_info_format='Извървяхте %d км, изгорихте %d cal.',

    get_over_format=", около %d грама мазнини.",
    click_to_get_help="Вижте какво може Mi Band.",
    take_a_walk="Разходете се с Mi Band.",
    take_a_walk_info="Mi Band ще проследява вашата активност, за да ви помогне да бъдете по-здрави.",
    unlock_hint="Отключвайте телефона си с Mi Band",
    unlock_hint_info="Открийте нов начин за защита на вашите лични данни.",
    no_data_hint_0="Бъдете активни, направете спорта част от вашия живот.",
    no_data_hint_1="Искате да останете щастливи? Просто потичайте.",
    no_data_hint_2="Кардио тренировката ще ви освежи и разнообрази всеки ден! ",
    no_data_hint_3="Обикновено човек прекарва 15%-20% от съня си в състояние на дълбок сън. ",
    not_binded_hint="Нямате свързана Mi Band към този профил, свържете сега. ",
    new_record_info="Уха! Току-що счупихте рекода по вървене.",
    new_record_format="Нов рекорд, %d крачки, %s %d",
    today_goal_reached="Поздравления! Днес вие постигнахте целта си. ",
    week_continue_reach_goal="Постигахте дневната си цел през цялата седмица! Каква страхотна седмица!",
    challenge_format="Постигнахте вашата цел през %d дни!",
    personal_best_format="Вашият рекорд е %d дни!",
    active_time_format_0="%dмин",
    active_time_format_1="%dч",
    active_time_format_2="%dч %d мин",
    activie_run_format_0="Пробягахте %s. Браво!",
    activie_run_format_1="Пробягахте %s. Справихте се фантастично!",
    activie_run_format_2="Пробягахте %s, Невероятна издръжливост!",
    activie_run_consumed="Изгорихте %d cal. %s",

    get_distance_format=", общо %d м.",
    activity_walk_format="%s Извървяхте %d крачки %s",
    activity_walk_consumed_format="Изгорихте %d cal %s",

    activity_activity_format="%s %s в движение %s",
    last_night_sleeped_good_format="През изминалата нощ спахте %s. Чудесен сън!",
    last_night_sleeped_normal_format="През изминалата нощ спахте %s.",
    deep_sleep_format="Дълбокият ви сън беше %s.",

    battery_low_info="Батерията е изтощена, моля заредете Mi Band.",
    battery_very_low_info="Свържете към зарядното",

    cannot_find_bracelet="Не можете да засечете вашата Mi Band?",
    cannot_find_bracelet_info="Уверете се, че вашата Mi Band има достатъчно енергия и е близо до телефона ви.",

    challenge_to_get="%s дни до поставянето на нов рекорд!",
    record_reach_max="Подобрихте си рекорда!",
    new_record_born="Нов рекорд!",
 }