-------------------------
-- Bulgarian Localization String resources
-- MIUI.BG (2014)
-- tmladenov
-------------------------
localization_Bulgarian_table = {
    calories_table={
        {str=" ",	calories=96},
        {str=" ",	calories=100},
        {str=" ",	calories=112},
        {str=" ",	calories=118},
        {str=" ",	calories=124},
        {str=" ",	calories=153},
        {str=" ",	calories=186},
        {str=" ",	calories=192},
        {str=" ",	calories=200},
        {str=" ",	calories=210},
        {str=" ",	calories=221},
        {str=" ",	calories=223},
        {str=" ",	calories=224},
        {str=" ",	calories=224},
        {str=" ",	calories=224},
        {str=" ",	calories=236},
        {str=" ",	calories=248},
        {str=" ",	calories=260},
        {str=" ",	calories=270},
        {str=" ",	calories=272},
        {str=" ",	calories=288},
        {str=" ",	calories=290},
        {str=" ",	calories=300},
        {str=" ",	calories=306},
        {str=" ",	calories=328},
        {str=" ",	calories=354},
        {str=" ",	calories=375},
        {str=" ",	calories=400},
        {str=" ",	calories=402},
        {str=" ",	calories=420},
        {str=" ",	calories=442},
        {str=" ",	calories=446},
        {str=" ",	calories=448},
        {str=" ",	calories=470},
        {str=" ",	calories=500},
        {str=" ",	calories=516},
        {str=" ",	calories=520},
        {str=" ",	calories=540},
        {str=" ",	calories=544},
        {str=" ",	calories=580},
        {str=" ",	calories=581},
        {str=" ",	calories=593},
        {str=" ",	calories=620},
        {str=" ",	calories=630},
        {str=" ",	calories=663},
        {str=" ",	calories=750},
        {str=" ",	calories=810},
        {str=" ",	calories=816},
    },

    ok='OK',

    hour='ч',
    minute='мин',
    month='месец',
    day='ден',
    step="крачка",
    km='км',
    minute_format='%dмин',
    hour_minute_format='%dч %dмин',
    hour_format='%dч',

    welcome_use="Здравей, аз съм твоята Mi Band.",
    last_week_walked_format='През последната седмица извървяхте %d крачки.',
    last_week_walked_info_format='Извървяхте %d км, изгорихте %d cal.',
    last_month_walked_format='През последния месец извървяхте %d крачки.',
    last_month_walked_info_format='Извървяхте %d км, изгорихте %d cal.',

    get_over_format=", около %d грама мазнини.",
    click_to_get_help="Вижте какво може Mi Band.",
    take_a_walk="Разходете се с Mi Band.",
    take_a_walk_info="Mi Band ще проследява вашата активност, за да ви помогне да бъдете по-здрави.",
    unlock_hint="Отключвайте телефона си с Mi Band",
    unlock_hint_info="открийте нов начин за защита на вашите лични данни.",
    no_data_hint_0="Бъдете активни, направете спорта част от вашия живот.",
    no_data_hint_1="Искате да останете щастливи? Просто потичайте.",
    no_data_hint_2="Кардио тренировката ще ви освежи и разнообрази всеки ден! ",
    no_data_hint_3="Обикновено човек прекарва 15%-20% от съня си в състояние на дълбок сън. ",
    not_binded_hint="Нямате свързана Mi Band към този профил, свържете сега. ",
    new_record_info="Уха! Току-що счупихте рекода по вървене.",
    new_record_format="Нов рекорд, %d крачки, %s %d",
    today_goal_reached="Поздравления! Днес вие постигнахте целта си. ",
    week_continue_reach_goal="Постигахте дневната си цел през цялата седмица! Каква страхотна седмица!",
    challenge_format="Постигнахте вашата цел през %d дни!",
    personal_best_format="Вашият рекорд е %d дни!",
    active_time_format_0="%dмин",
    active_time_format_1="%dч",
    active_time_format_2="%dч %d мин",
    activie_run_format_0="Пробягахте %s. Браво!",
    activie_run_format_1="Пробягахте %s. Справихте се фантастично!",
    activie_run_format_2="Пробягахте %s, Невероятна издръжливост!",
    activie_run_consumed="Изгорихте %d cal. %s",

    get_distance_format=", общо %d м.",
    activity_walk_format="%s Извървяхте %d крачки %s",
    activity_walk_consumed_format="Изгорихте %d cal %s",

    activity_activity_format="%s %s в движение %s",
    last_night_sleeped_good_format="През изминалата нощ спахте %s. Чудесен сън!",
    last_night_sleeped_normal_format="През изминалата нощ спахте %s.",
    deep_sleep_format="Дълбокият ви сън беше %s.",

    battery_low_info="Батерията е изтощена, моля заредете Mi Band.",
    battery_very_low_info="Свържете към зарядното",

    cannot_find_bracelet="Не можете да засечете вашата Mi Band?",
    cannot_find_bracelet_info="Уверете се, че вашата Mi Band има достатъчно енергия и е близо до телефона ви.",

    challenge_to_get="%s дни до поставянето на нов рекорд!",
    record_reach_max="Подобрихте си рекорда!",
    new_record_born="Нов рекорд!",
 }