-------------------------
-- Bulgarian Localization String resources
-- MIUI.BG (2014)
-- tmladenov
-------------------------
localization_Bulgarian_table = {
    calories_table={
        {str="≈2 варени яйца",	calories=96},
        {str="≈1 филийка хляб",	calories=100},
        {str="≈1 студен чай",	calories=112},
        {str="≈1 пържено яйце",	calories=118},
        {str="≈2 шишчета",	calories=124},
        {str="≈1 кутийка Кока-Кола",	calories=153},
        {str="≈3 шишчета",	calories=186},
        {str="≈4 варени яйца",	calories=192},
        {str="≈2 филийки хляб",	calories=200},
        {str="≈1 чаша ориз",	calories=210},
        {str="≈1 хляб",	calories=221},
        {str="≈1 кутия бонбони",	calories=223},
        {str="≈2 plechovky ľadového čaju",	calories=224},
        {str="≈1 malé hranolky",	calories=224},
        {str="≈1 tartelette",	calories=224},
        {str="≈2 omeletys",	calories=236},
        {str="≈4 mäsá na špajdli",	calories=248},
        {str="≈1 hamburger",	calories=260},
        {str="≈1 beignet",	calories=270},
        {str="≈1 petit pain de viande",	calories=272},
        {str="≈3 duo z varených vajec",	calories=288},
        {str="≈1 cône",	calories=290},
        {str="≈3 krajce chleba",	calories=300},
        {str="≈2 canettes de Coca-Cola",	calories=306},
        {str="≈1 moyenne frite",	calories=328},
        {str="≈3 omeletys",	calories=354},
        {str="≈1 tartelette aux œufs",	calories=375},
        {str="≈4 krajce chleba",	calories=400},
        {str="≈1 grande frite",	calories=402},
        {str="≈2 bols de riz",	calories=420},
        {str="≈2 pains",	calories=442},
        {str="≈2 paquet de dragibus",	calories=446},
        {str="≈2 tartelettes",	calories=448},
        {str="≈1 paquet de nouilles instantanées",	calories=470},
        {str="≈5 krajce chleba",	calories=500},
        {str="≈1 assiette de riz frit",	calories=516},
        {str="≈2 hamburgers",	calories=520},
        {str="≈2 beignets",	calories=540},
        {str="≈2 petits pains de viande",	calories=544},
        {str="≈2 cônes",	calories=580},
        {str="≈1 bol de nouilles instantanées",	calories=581},
        {str="≈1 bol de nouilles au boeuf",	calories=593},
        {str="≈10 mäsá na špajdli",	calories=620},
        {str="≈3 bols de riz",	calories=630},
        {str="≈3 pains",	calories=663},
        {str="≈2 tartelettes aux œufs",	calories=750},
        {str="≈3 beignets",	calories=810},
        {str="≈3 petits pains de viande",	calories=816},
    },

    ok='OK',

    hour='hrs',
    minute='min',
    month='month',
    day='day',
    step="step",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%d hrs %d min',
    hour_format='%d hrs',

    welcome_use="Hello, I am your Mi Band.",
    last_week_walked_format='Last week, you walked %d steps.',
    last_week_walked_info_format='Walked %d km, burned %d cal.',
    last_month_walked_format='Last month, you walked %d steps.',
    last_month_walked_info_format='Walked %d km, burned %d cal.',

    get_over_format=", about %d gram of fat.",
    click_to_get_help="Find out more to do with Mi Band.",
    take_a_walk="Take a walk with Mi Band.",
    take_a_walk_info="Mi Band will track your activities and help you to be healthier.",
    unlock_hint="Unlock phone with your Mi Band",
    unlock_hint_info="say Goodbye to the old times.",
    no_data_hint_0="Keep moving, make sports a part of your life.",
    no_data_hint_1="Want to stay happy? Just run.",
    no_data_hint_2="Cardio workout will make you light and fresh every day! ",
    no_data_hint_3="A normal adult spends 15%-20% of total sleep time in deep sleep stage. ",
    not_binded_hint="You haven’t linked any Mi Band to this account, please link one now. ",
    new_record_info="WoW! You just broke a record in walking.",
    new_record_format="New record, %d steps, %s %d",
    today_goal_reached="Congrats! You have achieved your goal today. ",
    week_continue_reach_goal="You have achieved your goal every day for an entire week! What an awesome week!",
    challenge_format="You have achieved your goal for %d days!",
    personal_best_format="Your highest record is %d days!",
    active_time_format_0="%d min",
    active_time_format_1="%d hr",
    active_time_format_2="%d hr %d min",
    activie_run_format_0="Ran %s. Good job!",
    activie_run_format_1="Ran %s. You are doing fantastic!",
    activie_run_format_2="Ran %s, Incredible endurance!",
    activie_run_consumed="Burned %d cal. %s",

    get_distance_format=", a total of %d m.",
    activity_walk_format="%s Walked %d steps %s",
    activity_walk_consumed_format="Burned %d cal %s",

    activity_activity_format="%s %s work out %s",
    last_night_sleeped_good_format="Last night, you slept for %s. What a great sleep!",
    last_night_sleeped_normal_format="Last night, you slept for %s.",
    deep_sleep_format="Deep sleep stage was %s.",

    battery_low_info="Low in battery, please charge your Mi Band.",
    battery_very_low_info="Connect to power",

    cannot_find_bracelet="Unable to find your Mi Band?",
    cannot_find_bracelet_info="Please make sure your Mi Band has power and stays nearby your phone.",

    challenge_to_get="%s days from making a new record!",
    record_reach_max="You have hit your highest record!",
    new_record_born="New record!",
 }